//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOTFEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SOTFEdit.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannibal.
        /// </summary>
        internal static string ActorClassification_cannibal {
            get {
                return ResourceManager.GetString("ActorClassification_cannibal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creep.
        /// </summary>
        internal static string ActorClassification_creep {
            get {
                return ResourceManager.GetString("ActorClassification_creep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string ActorClassification_human {
            get {
                return ResourceManager.GetString("ActorClassification_human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muddy Cannibal.
        /// </summary>
        internal static string ActorClassification_muddy_cannibal {
            get {
                return ResourceManager.GetString("ActorClassification_muddy_cannibal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal.
        /// </summary>
        internal static string ActorClassiification_animal {
            get {
                return ResourceManager.GetString("ActorClassiification_animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string ActorGender_female {
            get {
                return ResourceManager.GetString("ActorGender_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string ActorGender_male {
            get {
                return ResourceManager.GetString("ActorGender_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup always.
        /// </summary>
        internal static string BackupMode_Default {
            get {
                return ResourceManager.GetString("BackupMode_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always keep original, one additional backup.
        /// </summary>
        internal static string BackupMode_InitialAndOne {
            get {
                return ResourceManager.GetString("BackupMode_InitialAndOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Backups.
        /// </summary>
        internal static string BackupMode_None {
            get {
                return ResourceManager.GetString("BackupMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep one backup and overwrite.
        /// </summary>
        internal static string BackupMode_One {
            get {
                return ResourceManager.GetString("BackupMode_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} backups have been restored. Deleted files were moved to the recycle bin.
        /// </summary>
        internal static string BackupsRestoredMessage {
            get {
                return ResourceManager.GetString("BackupsRestoredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups restored.
        /// </summary>
        internal static string BackupsRestoredTitle {
            get {
                return ResourceManager.GetString("BackupsRestoredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cave or Bunker.
        /// </summary>
        internal static string GraphMask_CaveOrBunker {
            get {
                return ResourceManager.GetString("GraphMask_CaveOrBunker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        internal static string GraphMask_Surface {
            get {
                return ResourceManager.GetString("GraphMask_Surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannibal.
        /// </summary>
        internal static string InfluenceType_Cannibal {
            get {
                return ResourceManager.GetString("InfluenceType_Cannibal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutant.
        /// </summary>
        internal static string InfluenceType_Creepy {
            get {
                return ResourceManager.GetString("InfluenceType_Creepy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string InfluenceType_Player {
            get {
                return ResourceManager.GetString("InfluenceType_Player", resourceCulture);
            }
        }
    }
}
