//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOTFEdit
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavegamePath
        {
            get
            {
                return ((string)(this["SavegamePath"]));
            }
            set
            {
                this["SavegamePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired
        {
            get
            {
                return ((bool)(this["UpgradeRequired"]));
            }
            set
            {
                this["UpgradeRequired"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdates
        {
            get
            {
                return ((bool)(this["CheckForUpdates"]));
            }
            set
            {
                this["CheckForUpdates"] = value;
            }
        }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
            public string MapWindowState
            {
                get
                {
                    return ((string)(this["MapWindowState"]));
                }
                set
                {
                    this["MapWindowState"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("0")]
            public int MapWindowScreenIndex
            {
                get
                {
                    return ((int)(this["MapWindowScreenIndex"]));
                }
                set
                {
                    this["MapWindowScreenIndex"] = value;
                }
            }
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastFoundVersion
        {
            get
            {
                return ((string)(this["LastFoundVersion"]));
            }
            set
            {
                this["LastFoundVersion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public string Theme
        {
            get
            {
                return ((string)(this["Theme"]));
            }
            set
            {
                this["Theme"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string ThemeAccent
        {
            get
            {
                return ((string)(this["ThemeAccent"]));
            }
            set
            {
                this["ThemeAccent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InitialAndOne")]
        public global::SOTFEdit.ApplicationSettings.BackupMode BackupMode
        {
            get
            {
                return ((global::SOTFEdit.ApplicationSettings.BackupMode)(this["BackupMode"]));
            }
            set
            {
                this["BackupMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSavegame
        {
            get
            {
                return ((string)(this["LastSavegame"]));
            }
            set
            {
                this["LastSavegame"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language
        {
            get
            {
                return ((string)(this["Language"]));
            }
            set
            {
                this["Language"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSavegameName
        {
            get
            {
                return ((string)(this["LastSavegameName"]));
            }
            set
            {
                this["LastSavegameName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun
        {
            get
            {
                return ((bool)(this["FirstRun"]));
            }
            set
            {
                this["FirstRun"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_null_")]
        public string SelectedMapGroups
        {
            get
            {
                return ((string)(this["SelectedMapGroups"]));
            }
            set
            {
                this["SelectedMapGroups"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string CompanionAddress
        {
            get
            {
                return ((string)(this["CompanionAddress"]));
            }
            set
            {
                this["CompanionAddress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35321")]
        public int CompanionPort
        {
            get
            {
                return ((int)(this["CompanionPort"]));
            }
            set
            {
                this["CompanionPort"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public short CompanionConnectTimeout
        {
            get
            {
                return ((short)(this["CompanionConnectTimeout"]));
            }
            set
            {
                this["CompanionConnectTimeout"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public global::SOTFEdit.ViewModel.MapType MapType
        {
            get
            {
                return ((global::SOTFEdit.ViewModel.MapType)(this["MapType"]));
            }
            set
            {
                this["MapType"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public short CompanionKeepAliveInterval
        {
            get
            {
                return ((short)(this["CompanionKeepAliveInterval"]));
            }
            set
            {
                this["CompanionKeepAliveInterval"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal CompanionMapPositionUpdateInterval
        {
            get
            {
                return ((decimal)(this["CompanionMapPositionUpdateInterval"]));
            }
            set
            {
                this["CompanionMapPositionUpdateInterval"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AskForBackups
        {
            get
            {
                return ((bool)(this["AskForBackups"]));
            }
            set
            {
                this["AskForBackups"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MapFilterHideCompleted
        {
            get
            {
                return ((bool)(this["MapFilterHideCompleted"]));
            }
            set
            {
                this["MapFilterHideCompleted"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public string MapFilterAreaFilter
        {
            get
            {
                return ((string)(this["MapFilterAreaFilter"]));
            }
            set
            {
                this["MapFilterAreaFilter"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public string MapFilterRequirementsFilter
        {
            get
            {
                return ((string)(this["MapFilterRequirementsFilter"]));
            }
            set
            {
                this["MapFilterRequirementsFilter"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MapFilterFullText
        {
            get
            {
                return ((string)(this["MapFilterFullText"]));
            }
            set
            {
                this["MapFilterFullText"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DonePoiIdListString
        {
            get
            {
                return ((string)(this["DonePoiIdListString"]));
            }
            set
            {
                this["DonePoiIdListString"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MapWindowLeft
        {
            get { return ((double)(this["MapWindowLeft"])); }
            set { this["MapWindowLeft"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MapWindowTop
        {
            get { return ((double)(this["MapWindowTop"])); }
            set { this["MapWindowTop"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double MapWindowWidth
        {
            get { return ((double)(this["MapWindowWidth"])); }
            set { this["MapWindowWidth"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double MapWindowHeight
        {
            get { return ((double)(this["MapWindowHeight"])); }
            set { this["MapWindowHeight"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConnect
        {
            get { return ((bool)(this["AutoConnect"])); }
            set { this["AutoConnect"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoReload
        {
            get { return ((bool)(this["AutoReload"])); }
            set { this["AutoReload"] = value; }
        }
    }
}
